# Use the commitizen / AngularJS commit message style
# See https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines for more information
COMMIT_MESSAGE_REGEX: /(?:^(feat|fix|docs|style|refactor|perf|test|chore|ci|build)(\(.{1,30}\))?:[ ].{5,100}$)(:?\n(?:\n{1,2}^.{1,100}$)+)?/m