[package]
name = "interledger-btp"
version = "0.4.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Bilateral Transfer Protocol (BTP) client and server services for Interledger.rs"
license = "Apache-2.0"
edition = "2018"
repository = "https://github.com/interledger-rs/interledger-rs"

[dependencies]
bytes = { version = "0.4.12", default-features = false }
byteorder = { version = "1.3.2", default-features = false }
chrono = { version = "0.4.9", default-features = false }
futures = { version = "0.1.29", default-features = false }
interledger-packet = { path = "../interledger-packet", version = "^0.4.0", default-features = false }
interledger-service = { path = "../interledger-service", version = "^0.4.0", default-features = false }
log = { version = "0.4.8", default-features = false }
num-bigint = { version = "0.2.3", default-features = false, features = ["std"] }
parking_lot = { version = "0.9.0", default-features = false }
quick-error = { version = "1.2.2", default-features = false }
rand = { version = "0.7.2", default-features = false, features = ["std"] }
stream-cancel = { version = "0.4.4", default-features = false }
tokio-executor = { version = "0.1.8", default-features = false }
tokio-timer = { version = "0.2.11", default-features = false }
tokio-tungstenite = { version = "0.9.0", default-features = false, features = ["tls", "connect"] }
tungstenite = { version = "0.9.1", default-features = false }
url = { version = "2.1.0", default-features = false }
warp = { version = "0.1.20", default-features = false, features = ["websocket"] }

[dev-dependencies]
hex = { version = "0.4.0", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
net2 = { version = "0.2.33", default-features = false }
tokio = { version = "0.1.22", default-features = false }
